
get  http://127.0.0.1:8000/api/packages/3 HTTP/1.1
content-type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA3OTY2MDcwLCJpYXQiOjE3MDc4Nzk2MTAsImp0aSI6ImNhNWU1YTY5MTdkNTRkMWI4NTE5MDg1MDA2YjliM2JjIiwidXNlcl9pZCI6MTJ9.59fZMzg4_KjT8lLozDyBW3lArBqVsrxWnxjaFmJXNmA

{
    "no_of_persons":4
}

###

POST  http://127.0.0.1:8000/api/register HTTP/1.1
content-type: application/json

{
    "email": "user5@gmail.com",
    "password": "user4@1234"
}

###

POST  http://127.0.0.1:8000/api/login/user HTTP/1.1
content-type: application/json

{
    "email": "user5@gmail.com",
    "password": "user4@1234"
}

###

POST  http://127.0.0.1:8000/api/login/user HTTP/1.1
content-type: application/json

{
    "email": "user5@gmail.com",
    "password": "user4@1234"
}

###

GET http://127.0.0.1:8000/api/profile HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA3OTY4NzEyLCJpYXQiOjE3MDc4ODIyNTIsImp0aSI6ImMzMzI4YzZmZjVkODQ1OGJiZDUwMmRkOWExZDM0MjM4IiwidXNlcl9pZCI6MjN9.1j3EMS9razJYBRHwILt6nP9w3EYk1W4bMbvF-0BGedo

{

}
# PUT  http://127.0.0.1:5000/package/update/cd5e37fe-b9f0-4337-bde9-f863bf56a584 HTTP/1.1
# content-type: application/json

# {
#     "packageDuration": 10
    
# }

# POST http://127.0.0.1:5000/package/add-image/cd5e37fe-b9f0-4337-bde9-f863bf56a584 HTTP/1.1
# content-type: application/json

# {
    
    
# }

# DELETE http://127.0.0.1:5000/package/delete-image/cd5e37fe-b9f0-4337-bde9-f863bf56a584/c0d525d2-315e-4a7b-a940-a71192e880aa HTTP/1.1
# content-type: application/json

# {
    
    
# }