# Generated by Django 4.2.10 on 2024-02-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0004_alter_places_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="packages",
            old_name="available_slots",
            new_name="days",
        ),
        migrations.RenameField(
            model_name="packages",
            old_name="package_id",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="packages",
            old_name="package_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="packages",
            old_name="price_per_person",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="packages",
            old_name="duration_in_days",
            new_name="slots",
        ),
    ]
